# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='meal',
        ),
    ]
